import { useState, useMemo } from "react";
import { Layout } from "@/components/Layout";
import { PageHeader } from "@/components/PageHeader";
import { PageNavigation } from "@/components/PageNavigation";
import { BookOpen, Search } from "lucide-react";
import { Input } from "@/components/ui/input";

interface GlossaryTerm {
  term: string;
  definition: string;
  related?: string[];
}

const glossaryTerms: GlossaryTerm[] = [
  {
    term: "Ambiguous Criterion",
    definition: "A criterion that lacks clear, measurable standards, making it difficult for two evaluators to reach the same conclusion. Ambiguous criteria often use subjective words like 'appropriate,' 'reasonable,' or 'sufficient' without defining what those mean in context.",
    related: ["Criterion", "Rubric", "Two-Reviewer Test"],
  },
  {
    term: "Atomic Criterion",
    definition: "A criterion that tests exactly one thing and can receive exactly one judgment. The opposite of a stacked criterion. Atomic criteria are preferred because they provide clear, actionable feedback.",
    related: ["Stacked Criterion", "Criterion"],
  },
  {
    term: "Criterion (pl. Criteria)",
    definition: "A single, specific requirement or standard used to evaluate an AI model's output. Each criterion should be atomic (testing one thing), self-contained (understandable on its own), and unambiguous (measurable and clear).",
    related: ["Rubric", "Atomic Criterion", "Stacked Criterion"],
  },
  {
    term: "Dataroom",
    definition: "A collection of source documents, files, and data provided to the AI model as context for completing a task. This simulates the real-world scenario where an analyst has access to company filings, market data, and other reference materials.",
    related: ["Input Files", "Task"],
  },
  {
    term: "Deliverable",
    definition: "The expected output or work product that the AI model should produce in response to a task. Common deliverables include Excel models, PowerPoint presentations, PDFs, and written analyses.",
    related: ["Output", "Task"],
  },
  {
    term: "Evaluation",
    definition: "The process of assessing an AI model's output against a rubric to determine quality and accuracy. Evaluators apply each criterion to judge whether the output meets the specified requirements.",
    related: ["Rubric", "Criterion", "Major Error", "Minor Error"],
  },
  {
    term: "Factual Accuracy",
    definition: "A rubric category that assesses whether the AI's output contains correct information, properly sourced data, and accurate calculations. Errors in factual accuracy are often considered major errors.",
    related: ["Major Error", "Rubric Category"],
  },
  {
    term: "Formatting",
    definition: "A rubric category that evaluates the visual presentation, structure, and professional appearance of the output. This includes proper number formatting, alignment, consistent styling, and adherence to banking conventions.",
    related: ["Minor Error", "Rubric Category"],
  },
  {
    term: "Hardcode",
    definition: "In financial modeling, a value that is manually entered (typed in) rather than calculated from a formula. Hardcodes are typically formatted in blue font to distinguish them from calculated cells. In the context of rubrics, hardcoded criteria refer to specific, literal requirements.",
    related: ["Formatting"],
  },
  {
    term: "Input Files",
    definition: "The source documents and data files provided to the AI model to complete a task. These may include Excel spreadsheets, PDFs, company filings, FactSet data pulls, and other reference materials.",
    related: ["Dataroom", "Task"],
  },
  {
    term: "Major Error",
    definition: "A significant mistake that renders the output fundamentally unusable or untrustworthy. Major errors include incorrect calculations, wrong data, missing critical components, or outputs that would mislead decision-makers. An output with a major error cannot be used without substantial rework.",
    related: ["Minor Error", "Evaluation"],
  },
  {
    term: "Minor Error",
    definition: "A small mistake that affects quality but doesn't fundamentally break the output. Minor errors include formatting inconsistencies, typos, slight misalignments, or small presentational issues. An output with only minor errors is still usable but needs polish.",
    related: ["Major Error", "Evaluation"],
  },
  {
    term: "Multi-Turn",
    definition: "A task structure where the AI model receives follow-up instructions or feedback after an initial response, simulating a back-and-forth conversation. This tests the model's ability to iterate and refine its work based on new information.",
    related: ["Task", "Single-Turn"],
  },
  {
    term: "Output",
    definition: "The work product generated by the AI model in response to a task. Outputs are evaluated against the rubric to assess quality. Common outputs include financial models, presentations, and written analyses.",
    related: ["Deliverable", "Evaluation"],
  },
  {
    term: "Prompt",
    definition: "The instruction or request given to the AI model that describes what task to perform. A well-crafted prompt is clear, specific, and provides necessary context. In Project Sapphire, prompts simulate real requests an investment banking analyst might receive.",
    related: ["Task", "Prompt Context"],
  },
  {
    term: "Prompt Context",
    definition: "Additional background information provided alongside the main prompt to help the AI understand the scenario, constraints, and expectations. This may include the user's role, company preferences, formatting requirements, and other relevant details.",
    related: ["Prompt", "Task"],
  },
  {
    term: "Rubric",
    definition: "A structured evaluation framework consisting of multiple criteria used to assess the quality of an AI model's output. A good rubric has clear, atomic, self-contained criteria organized into logical categories with appropriate weights.",
    related: ["Criterion", "Evaluation", "Rubric Category", "Rubric Weights"],
  },
  {
    term: "Rubric Category",
    definition: "A grouping of related criteria within a rubric. Common categories include Factual Accuracy, Completeness, Formatting, and Methodology. Categories help organize evaluation and may have different weights reflecting their importance.",
    related: ["Rubric", "Criterion", "Rubric Weights"],
  },
  {
    term: "Rubric Weights",
    definition: "Numerical values assigned to criteria or categories that reflect their relative importance in the overall evaluation. Higher weights indicate more critical requirements. Weights help prioritize what matters most in the output.",
    related: ["Rubric", "Rubric Category"],
  },
  {
    term: "Self-Contained Criterion",
    definition: "A criterion that can be understood and evaluated without referring to other criteria, external documents, or unstated context. Self-contained criteria include all necessary information within their text, making evaluation consistent and clear.",
    related: ["Criterion", "Atomic Criterion"],
  },
  {
    term: "Single-Turn",
    definition: "A task structure where the AI model receives one prompt and produces one response without follow-up interaction. This is the simpler task format compared to multi-turn conversations.",
    related: ["Multi-Turn", "Task"],
  },
  {
    term: "Stacked Criterion",
    definition: "A criterion that combines multiple requirements into one, making it unclear how to score when some parts pass and others fail. Stacked criteria should be split into separate atomic criteria. Example: 'The table is formatted correctly AND includes all required data' is stacked.",
    related: ["Atomic Criterion", "Criterion"],
  },
  {
    term: "Task",
    definition: "A complete assignment given to the AI model, consisting of a prompt, any necessary input files, and expected deliverables. Tasks in Project Sapphire simulate real investment banking work like building models, creating presentations, or analyzing data.",
    related: ["Prompt", "Input Files", "Deliverable"],
  },
  {
    term: "Two-Reviewer Test",
    definition: "A mental check for criterion quality: if two different evaluators would likely reach the same conclusion when applying a criterion, it passes. If reasonable people might disagree, the criterion is probably ambiguous and needs clarification.",
    related: ["Ambiguous Criterion", "Criterion"],
  },
];

export default function Glossary() {
  const [searchQuery, setSearchQuery] = useState("");

  const filteredTerms = useMemo(() => {
    if (!searchQuery.trim()) return glossaryTerms;
    const query = searchQuery.toLowerCase();
    return glossaryTerms.filter(
      (item) =>
        item.term.toLowerCase().includes(query) ||
        item.definition.toLowerCase().includes(query) ||
        item.related?.some((r) => r.toLowerCase().includes(query))
    );
  }, [searchQuery]);

  const groupedTerms = useMemo(() => {
    const groups: Record<string, GlossaryTerm[]> = {};
    filteredTerms.forEach((term) => {
      const letter = term.term[0].toUpperCase();
      if (!groups[letter]) groups[letter] = [];
      groups[letter].push(term);
    });
    return groups;
  }, [filteredTerms]);

  const letters = Object.keys(groupedTerms).sort();

  return (
    <Layout>
      <div className="container mx-auto px-4 py-8 max-w-4xl">
        <PageHeader
          icon={BookOpen}
          title="Glossary"
          description="Key terms and definitions for Project Sapphire."
        />

        {/* Search Bar */}
        <div className="relative mt-8 mb-8">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
          <Input
            type="text"
            placeholder="Search terms..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="pl-10"
          />
        </div>

        {/* Letter Navigation */}
        <div className="flex flex-wrap gap-2 mb-8 pb-4 border-b border-border">
          {letters.map((letter) => (
            <a
              key={letter}
              href={`#letter-${letter}`}
              className="w-8 h-8 flex items-center justify-center rounded-md text-sm font-medium text-muted-foreground hover:bg-primary/10 hover:text-primary transition-colors"
            >
              {letter}
            </a>
          ))}
        </div>

        {/* Terms */}
        <div className="space-y-12">
          {letters.map((letter) => (
            <div key={letter} id={`letter-${letter}`}>
              <h2 className="text-2xl font-bold text-primary mb-6 sticky top-16 bg-background py-2 border-b border-border">
                {letter}
              </h2>
              <div className="space-y-6">
                {groupedTerms[letter].map((item) => (
                  <div
                    key={item.term}
                    className="p-6 rounded-lg border border-border bg-card hover:border-primary/30 transition-colors"
                  >
                    <h3 className="text-lg font-semibold text-foreground mb-2">
                      {item.term}
                    </h3>
                    <p className="text-muted-foreground leading-relaxed mb-3">
                      {item.definition}
                    </p>
                    {item.related && item.related.length > 0 && (
                      <div className="flex flex-wrap gap-2">
                        <span className="text-xs text-muted-foreground">Related:</span>
                        {item.related.map((related) => (
                          <span
                            key={related}
                            className="text-xs px-2 py-1 rounded-full bg-primary/10 text-primary cursor-pointer hover:bg-primary/20 transition-colors"
                            onClick={() => setSearchQuery(related)}
                          >
                            {related}
                          </span>
                        ))}
                      </div>
                    )}
                  </div>
                ))}
              </div>
            </div>
          ))}
        </div>

        {filteredTerms.length === 0 && (
          <div className="text-center py-12">
            <BookOpen className="h-12 w-12 text-muted-foreground mx-auto mb-4" />
            <p className="text-muted-foreground">
              No terms found matching "{searchQuery}"
            </p>
          </div>
        )}

        <PageNavigation />
      </div>
    </Layout>
  );
}

